/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/*
 * Class:     net_fitcome_jnidemo_JniUtil
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_net_fitcome_jnidemo_JniUtil_getJniString
    (JNIEnv *env, jobject arg)
  {
        jstring str = (*env)->NewStringUTF(env, "HelloWorld from JNI !");
        return str;
  }

/*
 * Class:     net_fitcome_jnidemo_JniUtil
 * Method:    getJniAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_fitcome_jnidemo_JniUtil_getJniAdd
  (JNIEnv *env, jobject arg, jint a, jint b)
  {
     return a + b;
  }