/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_fitcome_jnidemo_JniUtil */

#ifndef _Included_net_fitcome_jnidemo_JniUtil
#define _Included_net_fitcome_jnidemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_fitcome_jnidemo_JniUtil
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_fitcome_jnidemo_JniUtil_getJniString
  (JNIEnv *, jobject);

/*
 * Class:     net_fitcome_jnidemo_JniUtil
 * Method:    getJniAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_fitcome_jnidemo_JniUtil_getJniAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
